### ISSUE TITLE
Ajouter mb_string aux dépendances et l'installer

### ISSUE THREAD

**Issue by rjullien** [NextDom/plugin-veolia_eau#50]
## Description
Le fait de passer par la lib excel ramène une dependence sur mb_string qui n'est pas installé par défaut. 
```
[2018-03-28 23:05:04][DEBUG] : ### TRAITE CONSO XLS 2 ###
[2018-03-28 23:05:04][ERROR] : Erreur sur la fonction cronHourly du plugin : Call to undefined function mb_strlen()
```
## Etapes à reproduire (pour les bugs)
1. Plante systèmatiquement sur RPI

## Proposition de solution (optionnel):
sudo apt-get install php7.0-mbstring

## Environnement:
* **Version Jeedom**: toutes
* **Platform**: RPI3
* **Version du Plugin**: latest

**Comment by damien916** [comment]
Hello, 
Bonne idée, comment fait-on pour ajouter une dépendance ? il y a ça qqpart dans le template ?

**Comment by rjullien** [comment]
Exemple pour relancer Apache
if [[ $EUID -ne 0 ]]; then
  sudo_prefix = "sudo";
fi

echo "### Autorisation de liens symboliques pour le serveur Web Apache ###"
cd "$(dirname "$0")"
if grep -q "Options FollowSymLinks" /etc/apache2/sites-available/000-default.conf ; then
  $sudo_prefix service apache2 reload
  echo "### Modification de la configuration d'Apache déjà effectuée ###"
else
  $sudo_prefix sed '/DocumentRoot \/var\/www\/html/r followLinks.txt'  /etc/apache2/sites-available/000-default.conf > /tmp/000-default_temp.conf
  $sudo_prefix mv /tmp/000-default_temp.conf /etc/apache2/sites-available/000-default.conf
  $sudo_prefix service apache2 reload
  echo "### Modification de la configuration d'Apache effectuée et appliquée ###"
fi
if grep -q "\-FollowSymLinks" /etc/apache2/conf-enabled/security.conf ; then
  $sudo_prefix sed -i "s|-FollowSymLinks| |g" /etc/apache2/conf-enabled/security.conf
  $sudo_prefix service apache2 reload
  echo "### Modification de la configuration de sécurité d'Apache effectuée et appliquée ###"
fi

**Comment by rjullien** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-RTSP/blob/master/plugin_info/install.php

**Comment by Jean-Mercier** [comment]
J'ai ajouter un merge request pour gerer les dependance a tester #64

**Comment by damien916** [comment]
Merci, je passe ça en bêta
