### ISSUE TITLE
Veolia IDF

### ISSUE THREAD

**Issue by Shaktohh** [NextDom/plugin-veolia_eau#71]
Hello,

Y-a-t-il une chance que le nouveau site Veolia IDF soit intégré ?

Tous les détails ici 👍 
https://www.jeedom.com/forum/viewtopic.php?f=140&t=21200&start=580#p674519

**Comment by damien916** [comment]
Hello,
Sans accès impossible de mettre en place, il faudrait un développeur qui est chez Veolia IDF.
qqun ?

**Comment by FabriceGo** [comment]
Bonjour Damien,

Si je te donne un accès à mon espace client (via MP sur le forum de Jeedom) ?
- Tu pense que cela peut aider ?

**Comment by damien916** [comment]
Hello, oui pas de soucis, si tu veux, change ton mot de passe avant, et tu pourra le rechanger après.

**Comment by FabriceGo** [comment]
C'est ce que j'ai fait :)

**Comment by FabriceGo** [comment]
Ok ba ce n'est pas grave, c'est surtout dommage pour nous.
- Ton plugin était vraiment synaptique.

**Comment by damien916** [comment]
Je suis vraiment désolé, je pense que petit à petit Veolia va migrer ses site, et le plugin va finir aux oubliettes :/

**Comment by sylvek** [comment]
Hello, j'avais commencé un petit projet similaire (https://github.com/sylvek/VeoliaConnect/) et j'ai le malheur d'habiter en île de France, alors effectivement, ça ne fonctionne plus chez moi non plus.
Je me dis qu'il y a tout de même une solution.. j'ai testé avec le plugin Selenium, mais le "re-jeu" ne fonctionne pas. Mais je souhaiterais profiter de ce fil de discussion pour relancer le sujet .. sauf si vous connaissez un endroit plus approprié.
