### ISSUE TITLE
test unitaire

### ISSUE THREAD

**Issue by guenneguezt** [NextDom/plugin-veolia_eau#72]
Bonjour,

J'ai vu que tu avais mis en place des tests unitaire sur ton plugin et rédigé une partie de la doc : https://github.com/NextDom/NextDom/wiki/Tester-un-plugin-avec-travis-ci#mocker-les-acces-externes
J'ai des questions, mais je ne sais pas où les poser pour que tu les vois ;-)
Je suis sur :
https://github.com/NextDom/NextDom/wiki/Tester-un-plugin-avec-travis-ci#mocker-les-acces-externes
Mais dans le plugin Template on a :
tests\mocked_Jeedom_env

Je comprends le tests\launch_tests.sh
Mais pas la dernière ligne ni l'interpretation du phpunit.xml

Je ne comprends pas non plus dans .travis.yml :
sed -i'' 's/tests\/mocked_Jeedom_env\/plugins\/ExtraTemplate\///g' clover.xml

Je travaille sur https://github.com/NextDom/plugin-ecodevice/tree/develop

Merci d'avance de ton retour
Thomas

**Comment by rjullien** [comment]
Bonsoir,

Je n ai pas eu le temps de regarder ce soir mais je peux trouver du temps
pour répondre, ca fait un moment il faut que je regarde le code.
Voila mon email direct: rene.jullien@gmail.com

René

Le mer. 13 nov. 2019 à 10:59, guenneguezt <notifications@github.com> a
écrit :
